v2.6.3

diff --git a/bin/tctconfig b/bin/tctconfig
--- a/bin/tctconfig
+++ b/bin/tctconfig
@@ -1,7 +1,7 @@
 #!/bin/bash
 #
 #Name:tctconfig
-#Version:2.6.2
+#Version:2.6.3
 #Auther：Daniel
 #Date&Time：2021年11月24日
 #Discription：实现通过脚本自动备份，重启，更新tomcat系统
@@ -13,14 +13,14 @@ set -m
 #获取文件运行的当前目录
 #BINPATH=$(cd "$(dirname "$0")"; pwd)
 
-VERSION=2.6.2
+VERSION=2.6.3
 
-#INSTALL_OPTION配置tctconfig为software模式或者是script模式;
-#如果INSTALL_OPTION配置为script模式，则设置tct.conf的路径为$HOME/tctconfig/conf/tct.conf,更新补丁及备份补丁路径为$HOME/tctconfig,日志路径为$HOME/tctconfig/logs
-#注释掉INSTALL_OPTION或者是配置其他值，则设置tct.conf的路径为/etc/tct.conf,更新补丁及备份补丁路径为$HOME/tctconfig，日志路径为/usr/local/logs,
+#INSTALL_OPTION=software配置tctconfig为software模式或者是script模式;
+#如果INSTALL_OPTION=software配置为script模式，则设置tct.conf的路径为$HOME/tctconfig/conf/tct.conf,更新补丁及备份补丁路径为$HOME/tctconfig,日志路径为$HOME/tctconfig/logs
+#注释掉INSTALL_OPTION=software或者是配置其他值，则设置tct.conf的路径为/etc/tct.conf,更新补丁及备份补丁路径为$HOME/tctconfig，日志路径为/usr/local/logs,
 #根据程序是software模式还是script模式来判断配置文件及日志文件的的路径
 #默认通过run文件install.sh脚本配置，也可自行配置
-INSTALL_OPTION=
+INSTALL_OPTION=script
 
 if [ $INSTALL_OPTION == script ];then
 	CONF_FILE=$HOME/tctconfig/conf/tct.conf
@@ -58,6 +58,12 @@ case $1 in
 	-tg|--tgupdate)
 		CONFIGURATION=tg
 		CONFIG_MODE=COMMON;;
+	-gt|--gtupdate)
+        CONFIGURATION=gt
+        CONFIG_MODE=COMMON;;
+	-qxbs|--qxbsupdate)
+        CONFIGURATION=qxbs
+        CONFIG_MODE=COMMON;;
 	-sh|--shutdown)
 		CONFIGURATION=sh
 		CONFIG_MODE=PRO;;
@@ -88,7 +94,8 @@ case $1 in
 			INSTALLOPTION=full;
 		fi;;
 	-c|--clean)
-		CONFIGURATION=c;;
+		CONFIGURATION=c
+		CLEAN_OPTION=$2;;
 	-v|--version)
 		echo -e "\033[33mThe tctconfig version is $VERSION\033[0m"
 		echo -e "\033[32mThe program path is $TCT_PATH\033[0m"
@@ -119,117 +126,153 @@ esac
 
 #备份对应系统
 backup() {
-        #echo "Start to backup $TOMCATVERSION..."
         cd $TOMCATPATH/webapps/
 	echo -e "\033[33mStart to backup $TOMCATPATH/webapps/$ROOTPATH\033[0m\nThe back file is $TOMCATPATH/webapps/$ROOTPATH`date +%Y-%m-%d-%H:%M`.zip" 2>&1| tee -a  $TCT_PATH/logs/tctconfig-`date +%Y-%m-%d`.log
         zip -r $ROOTPATH`date +%Y-%m-%d-%H:%M`.zip $ROOTPATH >>$TCT_PATH/logs/$TOMCATVERSION-backup-`date +%Y-%m-%d`.log
 	echo -e "\033[32m$TOMCATPATH/webapps/$ROOTPATH backup successfully.\033[0m" 2>&1|tee -a $TCT_PATH/logs/tctconfig-`date +%Y-%m-%d`.log
-	#echo "$TOMCATVERSION backup successfully!!!"
 
 }
 
 #测试之前的完整备份
 testbackup() {
-        #echo "Start to backup $TOMCATVERSION before test..."
         cd $TOMCATPATH/webapps/
 	echo -e "\033[33mStart to backup $TOMCATPATH/webapps/$ROOTPATH before test...\033[0m\nThe back file is $TOMCATPATH/webapps/$ROOTPATH`date +%Y-%m-%d-%H:%M`TB.zip" 2>&1 | tee -a $TCT_PATH/logs/tctconfig-`date +%Y-%m-%d`.log
         zip -r $ROOTPATH`date +%Y-%m-%d-%H:%M`TB.zip $ROOTPATH >> $TCT_PATH/logs/$TOMCATVERSION-backup-`date +%Y-%m-%d`.log
 	echo -e "\033[32m$TOMCATPATH/webapps/$ROOTPATH backup before test successfully.\033[0m" 2>&1 | tee -a $TCT_PATH/logs/tctconfig-`date +%Y-%m-%d`.log
-	#echo "$TOMCATVERSION backup before test successfully!!!"
 }
 #关闭对应tomcat
 tctshut(){
-	#echo "Start to shutdown $TOMCATVERSION..."
-        #关闭对应的tomcat
-        #echo "$TOMCATVERSION is shuting..."
+    #关闭对应的tomcat
 	echo -e "\033[36mStart to shut $TOMCATPATH/webapps/$ROOTPATH\033[0m" 2>&1| tee -a $TCT_PATH/logs/tctconfig-`date +%Y-%m-%d`.log
 	cd $TOMCATPATH
 	$TOMCATPATH/bin/shutdown.sh &>/dev/null
         sleep 3
 	ps -ef | grep $TOMCATPATH | grep -v grep | awk '{print $2}' | sed -e "s/^/kill -9 /g" | sh -
 	echo -e "\033[33m$TOMCATPATH/webapps/$ROOTPATH is shutted successfully\033[0m" 2>&1|tee -a $TCT_PATH/logs/tctconfig-`date +%Y-%m-%d`.log
-	#echo "$TOMCATVERSION is shutted successfully..."
 	sleep 1
 }
 #开启对应tomcat
 tctstart(){
  	#启动tomcat,并查看对应日志
-        #echo "$TOMCATVERSION is starting..." 
-        #sleep 1
 	echo -e "\033[32mStarting $TOMCATPATH/webapps/$ROOTPATH ...\033[0m" 2>&1| tee -a $TCT_PATH/logs/tctconfig-`date +%Y-%m-%d`.log
 	cd $TOMCATPATH
 	$TOMCATPATH/bin/startup.sh >>$TCT_PATH/logs/tctconfig-`date +%Y-%m-%d`.log
 	#echo -e "\033[31m$TOMCATPATH/webapps/$ROOTPATH start successfully\033[0m" 2>&1| tee -a $TCT_PATH/logs/tctconfig-`date +%Y-%m-%d`.log
         tail -f $TOMCATPATH/logs/catalina.out
-        #ps -ef | grep ^tctconfig | grep -v grep | awk '{print $2}' | sed -e "s/^/kill -9 /g" | sh -
 }
 tctrestart(){
 	tctshut
 	tctstart
 }
-#检查TOMCATVERSION是否合法
-TOMCAT_CHECK(){
-
+#检查TOMCATVERSION是否合法,并获取对应配置文件
+TOMCAT_GET(){
+	#判断是否正确输入了参数
 	if [ -z $TOMCATVERSION ];then
-        	echo "error,Please choose a system to configure";
-        	exit 7;
-        elif [ `cat $CONF_FILE | grep ^$TOMCATVERSION | wc -l` -gt 1 ];then
-        	echo "The $TOMCATVERSION is more than one in tct.conf,Please check it";
-        	exit 8;
-        elif [ `cat $CONF_FILE | grep ^$TOMCATVERSION | wc -l` -lt 1 ];then
-		echo "The $TOMCATVERSION is not exist in tct.conf,Please check it";
-                exit 9;
+		echo "error,Please choose a system to configure";
+		exit 7;
+	#判断输入的TOMCATVERSION，是否为MULTI_name里的值，如果是的话进行多个更新，不是就正常获取tomcat路径
+	elif [ -n "`cat $CONF_FILE | grep ^MULTI | cut -d : -f 1 | grep $TOMCATVERSION`" ];then
+		MULTI_NAME=$TOMCATVERSION
+		MULTI_COUNT=`cat $CONF_FILE | grep ^MULTI | grep $MULTI_NAME | cut -d : -f 2 | awk '{print NF}'`
+		I=1
+		while [ $I -le $MULTI_COUNT ];do
+			TOMCATVERSION=`cat $CONF_FILE | grep ^MULTI | grep $MULTI_NAME | cut -d : -f 2 | awk -F ' ' '{ print $'$I'}'`	
+			TOMCATPATH=`cat $CONF_FILE | grep ^$TOMCATVERSION | awk -F':' '{ print $2 }'`
+	               	ROOTPATH=`cat $CONF_FILE | grep ^$TOMCATVERSION | awk -F':' '{ print $3 }'`
+			TOMCAT_CONFIGURE		
+			let I++
+		done;
+		exit 0;
+	else
+        	if [ `cat $CONF_FILE | grep ^$TOMCATVERSION | wc -l` -gt 1 ];then
+               		echo "The $TOMCATVERSION is more than one in tct.conf,Please check it";
+               		exit 8;
+        	elif [ `cat $CONF_FILE | grep ^$TOMCATVERSION | wc -l` -lt 1 ];then
+               		echo "The $TOMCATVERSION is not exist in tct.conf,Please check it";
+               		exit 9;
+       		fi
+		TOMCATPATH=`cat $CONF_FILE | grep ^$TOMCATVERSION | awk -F':' '{ print $2 }'`;
+		ROOTPATH=`cat $CONF_FILE | grep ^$TOMCATVERSION | awk -F':' '{ print $3 }'`;
 	fi
 }
 #进行日常更新
 update() {
-
-	#关闭对应tomcat
+	if [ -z "`ls -A $PACKAGE_PATH/package/update`" ];then
+        	echo -e "\033[31merror\033[0m,Update files don't exist,Please put it in $PACKAGE_PATH/package/update/";
+        	exit 4
+	else	
+		echo -e "\033[34mStart to update $TOMCATPATH/webapps/$ROOTPATH\033[0m" 2>&1| tee -a $TCT_PATH/logs/tctconfig-`date +%Y-%m-%d`.log
+	        \cp -a $PACKAGE_PATH/package/update/* $TOMCATPATH/webapps/$ROOTPATH 2>&1| tee -a $TCT_PATH/logs/tctconfig-`date +%Y-%m-%d`.log
+		sleep 3
+		echo -e "\033[34m$TOMCATPATH/webapps/$ROOTPATH update successfully\033[0m" 2>&1| tee -a $TCT_PATH/logs/tctconfig-`date +%Y-%m-%d`.log
+		sleep 2
+	fi
+}
+#清理更新文件
+updateclean(){
+	#备份本次更新文件
+        if [ $MULTI_COUNT -gt 1 ];then
+		mkdir -p $PACKAGE_PATH/package/backup/$MULTI_NAME/`date +%Y-%m-%d-%H:%M`/
+                mv $PACKAGE_PATH/package/update/* $PACKAGE_PATH/package/backup/$MULTI_NAME/`date +%Y-%m-%d-%H:%M`/ 2>&1| tee -a $TCT_PATH/logs/tctconfig-`date +%Y-%m-%d`.log
+	else
+		mkdir -p $PACKAGE_PATH/package/backup/$TOMCATVERSION/`date +%Y-%m-%d-%H:%M`/
+        	mv $PACKAGE_PATH/package/update/* $PACKAGE_PATH/package/backup/$TOMCATVERSION/`date +%Y-%m-%d-%H:%M`/ 2>&1| tee -a $TCT_PATH/logs/tctconfig-`date +%Y-%m-%d`.log
+	fi
+}
+fullupdate(){
 	tctshut
-	#切换到当前应用程序的目录
-	#cd $TCT_PATH
-        #进行文件更新
-        #echo "Start to update $TOMCATVERSION..."
-	echo -e "\033[34mStart to update $TOMCATPATH/webapps/$ROOTPATH\033[0m" 2>&1| tee -a $TCT_PATH/logs/tctconfig-`date +%Y-%m-%d`.log
-        #sleep 2
-        \cp -a $PACKAGE_PATH/package/update/* $TOMCATPATH/webapps/$ROOTPATH 2>&1| tee -a $TCT_PATH/logs/tctconfig-`date +%Y-%m-%d`.log
-        #删除本次更新文件
-	mkdir -p $PACKAGE_PATH/package/backup/$TOMCATVERSION/`date +%Y-%m-%d-%H:%M`/
-        mv $PACKAGE_PATH/package/update/* $PACKAGE_PATH/package/backup/$TOMCATVERSION/`date +%Y-%m-%d-%H:%M`/ 2>&1| tee -a $TCT_PATH/logs/tctconfig-`date +%Y-%m-%d`.log
-	sleep 3
-	#echo "$TOMCATVERSION is updated successfully!"
-	echo -e "\033[34m$TOMCATPATH/webapps/$ROOTPATH update successfully\033[0m" 2>&1| tee -a $TCT_PATH/logs/tctconfig-`date +%Y-%m-%d`.log
-        #重启tomcat
-        echo "Start to start $TOMCATPATH/webapps/$ROOTPATH..." 2>&1| tee -a $TCT_PATH/logs/tctconfig-`date +%Y-%m-%d`.log
-	sleep 2
-	#开启对应tomcat
+	update
+	updateclean
 	tctstart
 }
 #配置同时更新多个tomcat
+#统一管理平台（tg）
 tgupdate(){
-#备份对应系统
-tctconfig -b zs
-tctconfig -b zyjj
-#同时更新两个对应系统
-if [ -z "`ls -A $PACKAGE_PATH/package/update`" ];then
-        echo -e "\033[31merror\033[0m,Update files don't exist,Please put it in $PACKAGE_PATH/package/update/";
-        exit 4
-else
-        echo -e "\033[34mStart to update tg\033[0m" 2>&1| tee -a $TCT_PATH/logs/tctconfig-`date +%Y-%m-%d`.log;
-        sleep 2;
-        \cp -a $PACKAGE_PATH/package/update/* /opt/webserver/tomcat8-zsfusion/webapps/zs 2>&1| tee -a $TCT_PATH/logs/tctconfig-`date +%Y-%m-%d`.log;
-        \cp -a $PACKAGE_PATH/package/update/* /opt/webserver/tomcat8-zyjjfusion/webapps/zyjj 2>&1| tee -a $TCT_PATH/logs/tctconfig-`date +%Y-%m-%d`.log;
-fi
-#删除本次更新文件
-mkdir -p $PACKAGE_PATH/package/backup/$TOMCATVERSION/`date +%Y-%m-%d-%H:%M`/
-mv $PACKAGE_PATH/package/update/* $PACKAGE_PATH/package/backup/$TOMCATVERSION/`date +%Y-%m-%d-%H:%M`/ 2>&1| tee -a $TCT_PATH/logs/tctconfig-`date +%Y-%m-%d`.log
-sleep 3
-#echo "$TOMCATVERSION is updated successfully!"
-echo -e "\033[34mtg update successfully\033[0m" 2>&1| tee -a $TCT_PATH/logs/tctconfig-`date +%Y-%m-%d`.log
-#重启tomcat
-echo "Start to restart tg" 2>&1| tee -a $TCT_PATH/logs/tctconfig-`date +%Y-%m-%d`.log
-tctconfig -r zs
-tctconfig -r zyjj
+#分别定义要部署的系统
+	TOMCATVERSION=df
+	TOMCAT_GET
+		backup
+			tctshut
+			update
+			tctstart		
+	TOMCATVERSION=zyjj
+	TOMCAT_GET
+		backup
+			tctshut
+			fullupdate
+			tctstart
+}
+#共通版（gt）
+gtupdate(){
+#分别定义要部署的系统
+	TOMCATVERSION=waibao
+	TOMCAT_GET
+		backup
+			tctshut
+			update
+			tctstart
+	TOMCATVERSION=tuoguan
+	TOMCAT_GET
+		backup
+			tctshut
+			fullupdate
+			tctstart
+}
+#期货协会报送系统(qxbs)
+qxbsupdate(){
+#分别定义要部署的系统
+	TOMCATVERSION=qhyxh
+	TOMCAT_GET
+		backup
+			tctshut
+			update
+			tctstart
+	TOMCATVERSION=shebao
+	TOMCAT_GET
+		backup
+			tctshut
+			fullupdate
+			tctstart
 }
 #redis启停配置
 redis_configure(){
@@ -245,7 +288,8 @@ case $REDIS_ACTION in
                         REDIS_CONF=`ls -l $REDIS_PATH/conf/ | grep conf | head -$I | tail -1 | cut -d ' ' -f9`
                         $REDIS_PATH/bin/redis-server $REDIS_PATH/conf/$REDIS_CONF
                         echo -e "\033[35mRedis  $REDIS_CONF is started successfully\033[0m" 2>&1|tee -a $TCT_PATH/logs/tctconfig-`date +%Y-%m-%d`.log
-                done
+         
+       done
                 echo -e "\033[34mStarting redis successfully\033[0m" 2>&1| tee -a $TCT_PATH/logs/tctconfig-`date +%Y-%m-%d`.log;;
 
         -sh|--shutdown)
@@ -271,7 +315,7 @@ case $REDIS_ACTION in
 esac
 }
 #清理参与进程,日志及备份文件
-clean(){
+cleanlog(){
 	rm -rf $PACKAGE_PATH/package/update/*
 	read -p "Do you want to clean the logs in $TCT_PATH/logs?(y for yes/n for no)" CLOG
 	case $CLOG in
@@ -281,6 +325,8 @@ clean(){
         	n)
                 	echo "Done nothing";;
 	esac
+}
+cleanbak(){
 	read -p "Do you want to clean the backups in $PACKAGE_PATH/package/backup?(y for yes/n for no)" CBAK
 	case $CBAK in
         	y)
@@ -289,9 +335,39 @@ clean(){
         	n)
                 	echo "Done nothing";;
 	esac
-	echo "Clean complete,exiting..."
-	sleep 1
-	ps -ef | grep tctconfig | grep -v grep | awk '{print $2}' | sed -e "s/^/kill -15 /g" | sh - &>/dev.null
+}
+cleancache(){
+	read -p "Do you want to clean the cache in Memory?(y for yes/n for no)" CACHE
+        case $CACHE in
+                y)
+
+                        echo "Start to clean cache"
+			sync;sync;sync #写入硬盘，防止数据丢失
+			sleep 10 #延迟10秒
+			echo 1 > /proc/sys/vm/drop_caches
+			echo 2 > /proc/sys/vm/drop_caches
+			echo 3 > /proc/sys/vm/drop_caches
+			echo "Clean cache uccessfully";;
+                n)
+                        echo "Done nothing";;
+        esac
+}
+clean(){
+	case $CLEAN_OPTION in
+	log)
+		cleanlog;;
+	bak)
+		cleanbak;;
+	cache)
+		cleancache;;
+	*)
+		cleanlog
+		cleanbak
+		cleancache
+		echo "Clean complete,exiting..."
+		sleep 1
+		ps -ef | grep tctconfig | grep -v grep | awk '{print $2}' | sed -e "s/^/kill -15 /g" | sh - &>/dev.null;;
+	esac
 }
 #安装部署解压
 #部署tomcat,redis,jdk
@@ -395,18 +471,24 @@ TOMCAT_CONFIGURE(){
                 	tctrestart;;
         	u)
                 	if [ -z "`ls -A $PACKAGE_PATH/package/update`" ];then
-                                echo -e "\033[31merror\033[0m,Update files don't exist,Please put it in $PACKAGE_PATH/package/update/";
-                                exit 4
+                        	echo -e "\033[31merror\033[0m,Update files don't exist,Please put it in $PACKAGE_PATH/package/update/";
+                        	exit 4
+                   	elif  [ $I -eq $MULTI_COUNT ];then
+                                backup;
+                                fullupdate;
+				exit 0;
                         else
-				backup
+				backup;
+				tctshut;
 				update;
+				tctstart;
 			fi;;
         	tu)
                 	if [ -z "`ls -A $PACKAGE_PATH/package/update`" ];then
                                 echo -e "\033[31merror\033[0m,Update files don't exist,Please put it in $PACKAGE_PATH/package/update/";
                         	exit 5;
 			else
-                                update;
+                                fullupdate;
                         fi;;
 		l)	
 	                tail -"$COUNT"f $TOMCATPATH/logs/catalina.out;;
@@ -431,13 +513,21 @@ case $CONFIGURATION in
                 else
                 	tgupdate;
                 fi;;
+	gt)
+		if [ -z "`ls -A $PACKAGE_PATH/package/update`" ];then
+                        echo -e "\033[31merror\033[0m,Update files don't exist,Please put it in $PACKAGE_PATH/package/update/";
+                        exit 5;
+                else
+                        gtupdate;
+                fi;;
+	qxbs)
+		qxbsupdate;;
 	c)
 		clean;;
         i)
                 install;;
         rd)
                 redis_configure;;
-
 	*)
 		if [ $CONFIG_MODE == PRO ];then
 	 		if [ $PROGRAM_MODE == single ];then
@@ -446,10 +536,8 @@ case $CONFIGURATION in
                 		ROOTPATH=`cat $CONF_FILE | grep ^SINGLE_PATH | awk -F':' '{ print $4 }'`;
 
         		else
-				TOMCATVERSION=$2
-				TOMCAT_CHECK;
-                        	TOMCATPATH=`cat $CONF_FILE | grep ^$TOMCATVERSION | awk -F':' '{ print $2 }'`;
-                        	ROOTPATH=`cat $CONF_FILE | grep ^$TOMCATVERSION | awk -F':' '{ print $3 }'`;
+				TOMCATVERSION=$2;
+                        	TOMCAT_GET;
         		fi;
 			TOMCAT_CONFIGURE;
 		else
@@ -458,9 +546,7 @@ case $CONFIGURATION in
                 		TOMCATPATH=`cat $CONF_FILE | grep ^SINGLE_PATH | awk -F':' '{ print $3 }'`;
                 		ROOTPATH=`cat $CONF_FILE | grep ^SINGLE_PATH | awk -F':' '{ print $4 }'`;
 			else
-               			TOMCAT_CHECK; 	
-				TOMCATPATH=`cat $CONF_FILE | grep ^$TOMCATVERSION | awk -F':' '{ print $2 }'`;
-               			ROOTPATH=`cat $CONF_FILE | grep ^$TOMCATVERSION | awk -F':' '{ print $3 }'`;
+				TOMCAT_GET;
 			fi;
 			TOMCAT_CONFIGURE;
 		fi;;
